{
  "errors": [],
  "failures": [
    {
      "test": "json_cabuloso_tests.TestKeyReplace.test_replace_flamarion_lucio",
      "traceback": "Traceback (most recent call last):\n  File \"/Users/fjorg1/Labs/mentoring/src/unittest/python/json_cabuloso_tests.py\", line 13, in test_replace_flamarion_lucio\n    self.assertTrue(result)\nAssertionError: False is not true\n"
    }
  ],
  "tests-run": 6
}